"""
Django settings for Zaikaa project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(pycr-ai9=z!8zpn+yu#uk1izne)gy$9++n+zkr42w6x4^&lla'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'food',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Zaikaa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',  # Add this line

            ],
        },
    },
]

WSGI_APPLICATION = 'Zaikaa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'zaikaa',
#         'USER': 'root',
#         'PASSWORD': 'abc123',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'zaikaa',  # Replace with your database name
        'USER': 'postgres',  # Replace with your database username
        'PASSWORD': '12345',  # Replace with your database password
        'HOST': 'localhost',  # Use the appropriate host (default is localhost)
        'PORT': '5432',  # Default PostgreSQL port
    }
}
DATABASE_URL = "postgresql://postgres:12345@localhost:5432/zaikaa"

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',  # Database name
#         'USER': 'postgres',  # Your RDS username
#         'PASSWORD': 'abcd1234',  # Your RDS password
#         'HOST': 'zaikaa2.chum8aeo6hwb.ap-south-1.rds.amazonaws.com',  # RDS Endpoint
#         'PORT': '5432',  # Default PostgreSQL port
#     }
# }
# at deployment

#DATABASE_URL="postgresql://postgres:abcd1234@zaikaa2.chum8aeo6hwb.ap-south-1.rds.amazonaws.com:5432/zaikaa"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False




# import os # deployment

STATIC_URL = '/static/' # both deployment and testing
# STATIC_ROOT = '/home/ubuntu/zaikaa/static'  # for deployment

STATICFILES_DIRS = [
    BASE_DIR / "food/static",  # Pointing to the correct folder inside the food app
]
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'food/static'),  # deployment
# ]


STATIC_ROOT = BASE_DIR / 'staticfiles'  # testing


# Razorpay credentials testing
RAZORPAY_KEY_ID = 'rzp_test_x6EYO4W3NIqb6X'
RAZORPAY_SECRET_KEY = 'XyLCQKkNiM9Mf5DIzRwReFEg'


# Razorpay credentials production
# RAZORPAY_KEY_ID = 'rzp_live_uJ1VIqrWCu5P0o'
# RAZORPAY_SECRET_KEY = 'Sd8tttdUJXKrhOWmZdXqMHNm'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = "ecell@sakec.ac.in"
EMAIL_HOST_PASSWORD = "doty lfzx shrx hanw"
EMAIL_USE_TLS = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Force the sender email
